version: 2.1

executors:
  windows_executor:
    machine:
      image: << parameters.windows_image >>
    parameters:
      windows_image:
        type: string

jobs:
  capture_screenshots:
    parameters:
      windows_image:
        type: string
    executor:
      name: windows_executor
      windows_image: << parameters.windows_image >>
    steps:
      - checkout
      - run:
          name: Take Screenshot
          command: |
            echo "Taking screenshot on << parameters.windows_image >>"
            # Lệnh chụp màn hình hoặc automation test tại đây
            # Ví dụ: powershell -Command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.SendKeys]::SendWait('{PRTSC}')"

workflows:
  version: 2
  capture_screenshots_workflow:
    jobs:
      - capture_screenshots:
          matrix:
            parameters:
              windows_image:
                - windows-server-2019
                - windows-server-2022
