version: 2.1

jobs:
  capture_screenshots:
    parameters:
      config_name:
        type: string
    machine:
      image: 'windows-server-2019-vs2019:stable'
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Run test with config << parameters.config_name >>
          command: |
            echo "Running on config: << parameters.config_name >>"
            mkdir results
            echo "Result for << parameters.config_name >>" > results/output.txt
            dir results

workflows:
  version: 2
  parallel_screenshots:
    jobs:
      - capture_screenshots:
          matrix:
            parameters:
              config_name:
                - test_case_a
                - test_case_b
                - test_case_c
