version: 2.1

parameters:
  windows_versions:
    type: enum
    enum:
      - windows-server-2019
      - windows-server-2022
    default: windows-server-2019

jobs:
  capture_screenshots:
    parameters:
      windows_version:
        type: string
    machine:
      image: 'windows-server-2019-vs2019:stable'
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Simulate Screenshot on << parameters.windows_version >>
          command: |
            echo "Simulating test on << parameters.windows_version >>"
            mkdir screenshots
            echo "Screenshot for << parameters.windows_version >>" > screenshots/screenshot.txt
            dir screenshots

workflows:
  version: 2
  capture_screenshots_workflow:
    jobs:
      - capture_screenshots:
          matrix:
            parameters:
              windows_version:
                - windows-server-2019
                - windows-server-2022
