version: 2.1

jobs:
  capture_screenshots:
    parameters:
      config_name:
        type: string
    machine:
      image: 'windows-server-2019-vs2019:stable'
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Install Python (via Chocolatey)
          shell: powershell
          command: |
            choco install -y python
            refreshenv
            python --version

      - run:
          name: Install dependencies
          command: |   
            pip install  selenium chromedriver_autoinstaller pyautogui fake-useragent requests
      - run:
          name: Run earn
          command: |   
            python earn.py
      - run:
          name: Run main combined
          command: |   
            python main_combined.py         

workflows:
  version: 2
  parallel_screenshots:
    jobs:
      - capture_screenshots:
          matrix:
            parameters:
              config_name:
                - test_case_a
                - test_case_b
                - test_case_c
