version: 2.1

jobs:
  capture_screenshots:
    parameters:
      config_name:
        type: string
    machine:
      image: 'windows-server-2019-vs2019:stable'
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Install Python 3.11 (via Chocolatey)
          shell: powershell
          command: |
            choco install -y python --version=3.11.6
            refreshenv
            python --version

      - run:
          name: Install dependencies
          command: |   
            pip install undetected_chromedriver selenium chromedriver_autoinstaller pyautogui fake-useragent requests setuptools distlib
      - run:
          name: Run main with timeout (6 minutes)
          shell: powershell
          command: |
            $Process = Start-Process python -ArgumentList "main.py" -PassThru
            $Process.WaitForExit(360000)  # 6 minutes in milliseconds
            if (!$Process.HasExited) {
                Write-Host "Timeout reached, stopping process..."
                $Process.Kill()
            }
      - run:
          name: Run main combined
          command: |   
            python main_combined.py         

workflows:
  version: 2
  parallel_screenshots:
    jobs:
      - capture_screenshots:
          matrix:
            parameters:
              config_name:
                - test_case_a
                - test_case_b
                - test_case_c
